----------------------------- TARGIL

1. RETURN FROM COMPNAY ONLY SALARY COLUMN
2. RETURN ID, NAME FOR RECORDS WHERE SALARY > 40000
3. RETURN * WHERE SALARY > AVG
4. RETURN * OF RECORD WHERE SALARY IS MAIMUM (HINT: MAX NESTED)
5. CREATE TABLE COMPANY_HIGH 
	(SAME COLUMNS AND CONSTRAINS AS COMPANY)
	INSERT ALL RECORDS WHERE SALARY > 40000

----------------------------- SOLUTION

-- 1. RETURN FROM COMPNAY ONLY SALARY COLUMN
SELECT SALARY FROM COMPANY;
-- 2. RETURN ID, NAME FOR RECORDS WHERE SALARY > 40000
SELECT ID, NAME FROM COMPANY
WHERE SALARY > 40000;
-- 3. RETURN * WHERE SALARY > AVG
SELECT * FROM COMPANY
WHERE SALARY > (SELECT AVG(SALARY) FROM COMPANY);
-- 4. RETURN * OF RECORD WHERE SALARY IS MAIMUM (HINT: MAX NESTED)
SELECT * FROM COMPANY
WHERE SALARY = (SELECT MAX(SALARY) FROM COMPANY);

--5. CREATE TABLE COMPANY_HIGH
--   (SAME COLUMNS AND CONSTRAINS AS COMPANY)
--   INSERT ALL RECORDS WHERE SALARY > 40000
create table COMPANY_HIGH
(
    ID      INTEGER not null
        primary key autoincrement,
    NAME    TEXT    not null,
    AGE     INT     not null,
    ADDRESS CHAR(50),
    SALARY  REAL
);
INSERT INTO COMPANY_HIGH(NAME, AGE, ADDRESS, SALARY)
SELECT NAME, AGE, ADDRESS, SALARY FROM COMPANY
WHERE SALARY >  40000;

--DROP TABLE COMPANY_HIGH;	
